services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    tty: true
    volumes:
      - .:/workspace/template-react-architecture
    environment:
      TZ: Asia/Tokyo
